services:
  fastapi-app:
    build: ./FastApi
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
      start_period: 20s